language: python
dist: trusty
sudo: required
python:
    - "3.5"
    - "3.6"
cache:
  pip: true
  directories:
    - node_modules
    - $HOME/.yarn-cache
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -qq install python-software-properties
  # Yarn Install: https://github.com/travis-ci/travis-ci/issues/6720#issuecomment-254988120
  # Repo for newer Node.js versions
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get -qq install yarn
  - yarn install
  - PATH=$(npm bin):$PATH
install: "pip install -r ./vagrant/requirements.txt"
script:
 - pytest vagrant/test/ --cov=vagrant/test/ --junitxml=./out_report.xml
 - jest
 - codecov

branches:
  only:
    - dev
    - master
