language: python
python:
    - "3.5"
    - "3.6"
cache:
 - pip
 - yarn
  directories:
    - node_modules
before_install:
  - sudo apt-get update -qq
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - sudo echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo yarn install
install: "pip install -r ./vagrant/requirements.txt"
script:
 - pytest vagrant/test/ --cov=vagrant/test/ --junitxml=./out_report.xml
 - codecov

 branches:
  only:
    - dev
    - master