language: python
python:
    - "3.5"
    - "3.6"
cache: pip
install: "pip install -r ./vagrant/app/requirements.txt"
script:
 - pytest vagrant/test/ --cov=vagrant/test/ --junitxml=./out_report.xml
 - codecov